# Project: test
# Makefile created by Dev-C++ 5.5.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o acllib.o
LINKOBJ  = main.o acllib.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -mwindows "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/libgdi32.a" "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/libkernel32.a" "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/libmsimg32.a" "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/libole32.a" "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/liboleaut32.a" "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/libuser32.a" "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/libuuid.a" "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/libwinmm.a" "../../../../../../../Program Files (x86)/Dev-Cpp/MinGW32/lib/libmsimg32.a"  -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.7.2/include/c++"
BIN      = test.exe
CXXFLAGS = $(CXXINCS) -g3 -DWINVER=0x0500
CFLAGS   = $(INCS) -g3 -DWINVER=0x0500
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

acllib.o: acllib.c
	$(CC) -c acllib.c -o acllib.o $(CFLAGS)
